name: Foo

on:
  workflow_dispatch:
 
jobs:
  build:
    permissions:
      contents: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      # - name: foo1
      #   run: >
      #     echo "hello!"




      # - name: shape json file
      #   run: sh shapeJsonLines.sh data.json

      - name: Zip
        run: zip data data.json

      - name: Remove json pages
        run: rm villagepump/pages/*.json

      - name: Split pages
        run: >
          deno run
          --allow-read
          --allow-write
          --no-check
          split.ts
      - name: Diff
        id: diff
        run: |
          git add -N villagepump/stats villagepump/pages
          git diff --name-only --exit-code
        continue-on-error: true

      - name: Commit files
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add villagepump/stats villagepump/pages
          git commit -m "Update"
          git push
        if: steps.diff.outcome == 'failure'

      - name: Set Date
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "data.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.CURRENT_DATETIME }}