name: Foo

on:
  workflow_dispatch:
 
jobs:
  build:
    permissions:
      contents: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10.4'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt

      - name: Remove old pages
        run: rm nishio/pages/*.json

      - name: Get new pages
        run: >
          python main.py

      - name: Commit files
        run: |
          set -x
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add nishio/stats nishio/pages
          git commit -m "Update pages"
          git push

      # - name: Set Date
      #   env:
      #     TZ: "Asia/Tokyo"
      #   run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # - name: Release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "data.zip"
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ env.CURRENT_DATETIME }}